### ISSUE TITLE
New unlicense project: zlog

### ISSUE THREAD

**Issue by zma** [unlicense/unlicense.org#28]
It is cool to have this "unlicense" license.

Release my logging library under unlicence: http://www.ericzma.com/projects/zlog/

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
