### ISSUE TITLE
New unlicensed project: Kalei Style Guide

### ISSUE THREAD

**Issue by hiulit** [unlicense/unlicense.org#29]
Here it is: https://github.com/hiulit/kaleistyleguide

Actually, this is a fork, so I don't know if you prefer to refer to the root project.

Thanks!

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
