### ISSUE TITLE
New unlicensed project: rss-bridge

### ISSUE THREAD

**Issue by mitsukarenai** [unlicense/unlicense.org#31]
Why open the web if it's with closed code ?
Happy to announce that already-PD project [RSS-Bridge](https://github.com/sebsauvage/rss-bridge) now conforms to UNLICENSE :sparkles:

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
