### ISSUE TITLE
New unlicensed project: Sassy-Gridlover

### ISSUE THREAD

**Issue by hiulit** [unlicense/unlicense.org#32]
https://github.com/hiulit/Sassy-Gridlover

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
