### ISSUE TITLE
POI: unlicense, public domain, and common knowledge

### ISSUE THREAD

**Issue by krattai** [unlicense/unlicense.org#33]
The usual disclaimer of IANAL.

In nature, there are no property rights.  Public Domain strives to assert that reality.  Certain jurisdictions do not recognize public domain.

There are certain suggestions that unlicense and other assertions of removing any legal encumbrance of creative and other content is somehow invalid.

I would submit that in the spirit of releasing some creative or other content and knowledge to "public domain" is simply a assertion and push of said content and knowledge to be COMMON KNOWLEDGE which, in most jurisdictions that I'm aware of, is thereby incapable of becoming legally encumbered under property or any other intellectual rights.

Comments?

**Comment by bendiken** [comment]
Closing this as these kinds of topics are better suited to be discussed on the [cc-community](https://lists.ibiblio.org/mailman/listinfo/cc-community) mailing list.
