### ISSUE TITLE
"new" unlicensed project: g3log

### ISSUE THREAD

**Issue by KjellKod** [unlicense/unlicense.org#38]
I would love to see g3log on the list at http://unlicense.org/
g3log : https://github.com/KjellKod/g3log

Cheers
KjellKod (author of g3log)

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
