### ISSUE TITLE
New unlicense project. 

### ISSUE THREAD

**Issue by Tombert** [unlicense/unlicense.org#39]
I wrote an MVC framework for Node.JS called Frameworkey: Promise Edition that uses the Unlicense. If wouldn't mind too much, I would greatly appreciate if you were to link to my project : D

**Comment by Tombert** [comment]
I shoudl probably put a link to this aforementioned project...My mistake: https://github.com/Tombert/frameworkeyPromiseEdition

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
