### ISSUE TITLE
Unlicensed library XML-string-to-PHP-array

### ISSUE THREAD

**Issue by gaarf** [unlicense/unlicense.org#42]
newly Unlicensed piece of code: https://github.com/gaarf/XML-string-to-PHP-array

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
