### ISSUE TITLE
New unlicense project

### ISSUE THREAD

**Issue by MJansson** [unlicense/unlicense.org#44]
Our foundation library

https://github.com/rampantpixels/foundation_lib

This library provides a cross-platform foundation library in C providing basic support data types and functions to write applications and games in a platform-independent fashion.

**Comment by LB--** [comment]
I think they said they stopped keeping up with unlicense projects because there are so many now.

**Comment by bendiken** [comment]
New submissions are welcome--but we are due to soon revamp the list of projects into something more akin to a database, where new submissions would be accepted as JSON files containing project metadata. I'll go ahead and add this project manually once we get that far...

**Comment by bendiken** [comment]
A belated answer, but indeed we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
