### ISSUE TITLE
New unlicensed projects: ImageTracer, simple image vectorizing in Javascript OR Java

### ISSUE THREAD

**Issue by jankovicsandras** [unlicense/unlicense.org#45]
Hi,

https://github.com/jankovicsandras/imagetracerjs - Simple raster image tracer and vectorizer written in JavaScript.
https://github.com/jankovicsandras/imagetracerandroid - Simple raster image tracer and vectorizer written in Java for Android 
https://github.com/jankovicsandras/imagetracerjava - Simple raster image tracer and vectorizer written in Java for desktop

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
