### ISSUE TITLE
New Unlicensed project: furl

### ISSUE THREAD

**Issue by gruns** [unlicense/unlicense.org#46]
It would be great to include furl in the list of Unlicensed Free Software on http://unlicense.org/.

  https://github.com/gruns/furl

How can I help?

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.

**Comment by gruns** [comment]
Awesome.

PR: https://github.com/unlicense/unencumbered-software/pull/1
