### ISSUE TITLE
new unlicense project

### ISSUE THREAD

**Issue by robertgins** [unlicense/unlicense.org#47]
We just released the source for one of our product using the unlicensed

https://github.com/BalsamicSolutions/RemarQ

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
