### ISSUE TITLE
 New unlicensed project: gl3w

### ISSUE THREAD

**Issue by skaslev** [unlicense/unlicense.org#51]
[gl3w](https://github.com/skaslev/gl3w) has been public domain since its inception. Can you add it to your list?

**Comment by bendiken** [comment]
A belated thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
