### ISSUE TITLE
New unlicensed project : KatWeb

### ISSUE THREAD

**Issue by kittyhacker101** [unlicense/unlicense.org#56]
https://github.com/kittyhacker101/KatWeb is a simple, static file webserver and reverse proxy, designed for the 21st century. It is now (I tried out another license, but I found it didn't suit my needs, so I switched it back), and will continue to be, for as long as this project exists, under the Unlicense.

**Comment by bendiken** [comment]
Thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
