### ISSUE TITLE
Unlicensed project: PHPWASkel

### ISSUE THREAD

**Issue by sirkadirov** [unlicense/unlicense.org#59]
**PHPWASkel** - a simple **PHP** **W**eb **A**pplication **Skel**eton for modern web apps written in PHP.

GitHub repo: https://github.com/SirkadirovTeam/PHPWASkel

**Comment by bendiken** [comment]
Thanks. Please note that we are no longer processing project additions here directly. If you wish to see your project listed, kindly resubmit as a pull request to the [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) registry where all project addition requests will be dealt with going forward.
