### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by johnjago** [unlicense/unlicense.org#64]
The certificate might have expired as https://unlicense.org gives the following error:

 Error 526 Ray ID: 4d9a434febd8254d • 2019-05-20 00:41:05 UTC

**Comment by trevoz** [comment]
Error 526 happens when Cloudflare is unable to successfully validate the SSL certificate on the origin web server and the SSL setting in the Cloudflare Crypto app is set to Full SSL (Strict) for the website.

**Comment by artob** [comment]
Overcome by events, I believe.
