### ISSUE TITLE
Yet another unlicensed project: libtgvoip (Telegram VoIP)

### ISSUE THREAD

**Issue by Kaffeine** [unlicense/unlicense.org#70]
[https://github.com/grishka/libtgvoip](https://github.com/grishka/libtgvoip/blob/public/UNLICENSE) is published as unlicensed software.

**Comment by Hexstream** [comment]
Please submit here instead: https://github.com/unlicense/unencumbered-software

**Comment by Kaffeine** [comment]
@Hexstream OK, will do.

I got here from the official site: https://unlicense.org/#unlicensed-free-software link "create a ticket" leads here.

**Comment by Hexstream** [comment]
Right, unfortunately it seems that the site is basically unmaintained at this time, pending a new redesign.
