### ISSUE TITLE
OSI approval

### ISSUE THREAD

**Issue by brettz9** [unlicense/unlicense.org#72]
Hi,

Per https://opensource.org/licenses/alphabetical , Unlicense is not listed as OSI approved. Have you attempted to become [OSI approved](https://opensource.org/approval)? I'd be curious to know the status if so, or if you are open to seeking the status if you have not, and if not, why not.

Thanks!

**Comment by Jorgen-P** [comment]
Unlicense seems to be listed there now.

**Comment by Hexstream** [comment]
Awesome!! [The Unlicense is now an OSI Approved License as of 12 june 2020.](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-June/004890.html)

(Had you seen this, @artob? This seems noteworthy.)
