### ISSUE TITLE
License URI

### ISSUE THREAD

**Issue by gkellogg** [unlicense/unlicense.org#74]
The difference between UNLICENSE and [Public Domain](https://creativecommons.org/licenses/publicdomain/) (now obsoleted in favor of [CC0](https://creativecommons.org/choose/zero/)) is obscure, if there is any.

As a license URI is commonly used on [Description of a Project](https://github.com/ewilderj/doap/wiki) files as the value of [doap:license](http://usefulinc.com/ns/doap#license), the difference might be described, but it would be good to have a specific versioned URL to use other than `https://unlicense.org/` as an appropriate value, or explicitly suggest using an appropriate Creative Commons URI.

**Comment by Hexstream** [comment]
My understanding is that the Unlicense is well-defined in all countries, whereas Public Domain is NOT well-defined in many countries.

**Comment by artob** [comment]
@gkellogg One option for an existing RDF URI would be https://unlicense.org/UNLICENSE, which contains the actual license text. In the unlikely event that there would be an Unlicense 2.0 in the future, that would definitely get a new, distinct URL.

Alternatively, we could go ahead and define an arbitrary and absolutely unambiguous URI, such as https://unlicense.org/1.0. I'm fine with either approach, let me know what you prefer.

@Hexstream This question is more about machine-readable URIs for ontologies than anything to do with legal matters.

**Comment by gkellogg** [comment]
I’d say the https://unlicense.org/1.0/ sends the right message, even thought there’s never likely the need for a 2.0, but who knows how regulation may affect the need for change.

It may also make sense for the link in the UNLICENCE text should refer there, rather than the site.

**Comment by artob** [comment]
@gkellogg We aren't changing the UNLICENSE text, it was bad enough to have to change it by a single character to migrate from HTTP to HTTPS :)

But OK, let's consider https://unlicense.org/1.0/ the canonical machine-readable URI for the 2009 revision of the Unlicense from hereon out. When I find the time, I'll sprinkle some JSON-LD over yonder when the site eventually gets rebooted (delayed due to current events).
