### ISSUE TITLE
Maybe add our project to "Unlicensed Free Software"

### ISSUE THREAD

**Issue by Linuxfabrik** [unlicense/unlicense.org#81]
[Linuxfabrik Monitoring-Plugins](https://git.linuxfabrik.ch/linuxfabrik/monitoring-plugins),  Enterprise Class Check Plugin Collection for Icinga, Nagios and other compatible monitoring applications.

**Comment by artob** [comment]
Kindly submit to [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) instead.

<img width="825" alt="Screenshot 2024-11-11 at 6 42 43 AM" src="https://github.com/user-attachments/assets/576b8fd9-ecbb-43fe-98de-9b0a5483b948">
