### ISSUE TITLE
New Unlicense project: nanoprintf

### ISSUE THREAD

**Issue by charlesnicholson** [unlicense/unlicense.org#83]
My printf implementation "nanoprintf" (https://github.com/charlesnicholson/nanoprintf) uses the Unlicense. Feel free to add it to your list if you like!

**Comment by DreamHollow** [comment]
This isn't really an issue with the project, no offense.

**Comment by artob** [comment]
Kindly submit to [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) instead.

<img width="825" alt="Screenshot 2024-11-11 at 6 42 43 AM" src="https://github.com/user-attachments/assets/576b8fd9-ecbb-43fe-98de-9b0a5483b948">
