### ISSUE TITLE
URL for Nightweb Incorrect

### ISSUE THREAD

**Issue by KM217** [unlicense/unlicense.org#84]
Unlicense.org has Nightweb listed as an Unlicense project, which it is, according to https://github.com/oakes/Nightweb. Additionally, according to https://github.com/oakes/Nightweb, the correct URL would be sekao.net/nightweb/

**Comment by artob** [comment]
Thanks for noting. Added Nightweb to the registry but delisted it from the website since it has been abandoned for a number of years.
