### ISSUE TITLE
Unlicensed: bvh construction, GPU ray tracing

### ISSUE THREAD

**Issue by jbikker** [unlicense/unlicense.org#86]
https://github.com/jbikker/bvh_article
Unlicense was exactly what I was looking for.

**Comment by artob** [comment]
Kindly submit to [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) instead.

<img width="825" alt="Screenshot 2024-11-11 at 6 42 43 AM" src="https://github.com/user-attachments/assets/576b8fd9-ecbb-43fe-98de-9b0a5483b948">
