### ISSUE TITLE
Project using the Unlicense: HotDIR

### ISSUE THREAD

**Issue by veganaize** [unlicense/unlicense.org#88]
Hi,

My project [HotDIR](https://veganaize.github.io/HotDIR/), which offers colorized file & folder listings at the Windows command prompt, utilizes the Unlicense.

<https://github.com/veganaize/HotDIR>

Thanks

**Comment by artob** [comment]
Kindly submit to [unlicense/unencumbered-software](https://github.com/unlicense/unencumbered-software) instead.

<img width="825" alt="Screenshot 2024-11-11 at 6 42 43 AM" src="https://github.com/user-attachments/assets/576b8fd9-ecbb-43fe-98de-9b0a5483b948">
