### ISSUE TITLE
unlicense.org website is down

### ISSUE THREAD

**Issue by kaizhu256** [unlicense/unlicense.org#89]
![image](https://github.com/unlicense/unlicense.org/assets/280571/399bb6e1-52b8-4a45-baf5-1098ab58cab6)

**Comment by konceptosociala** [comment]
2 days later. It's still down :(

**Comment by konceptosociala** [comment]
I've created a fork to make the website accessible
https://konceptosociala.eu.org/unlicense/

**Comment by XtroTheArctic** [comment]
Months later, still down :(

**Comment by Hexstream** [comment]
What's the status on this, @artob? This is important...

**Comment by minacle** [comment]
Still down. Any updates, @artob?

Or, you abandoned Unlicense?

**Comment by Pyr3z** [comment]
Sad :(

It still seems down but perhaps with a different (or progressed) issue.

I simply get `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`, and given that it was previously pointing to a prohibited IP I wouldn't doubt that the site has been compromised to an attacker.

Responds to ping, ports 80 and 443 are accepting telnet connections, but `curl -v https://unlicense.org` gives

> `error:0A000410:SSL routines::sslv3 alert handshake failure`

= the site either suffered from a downgrade attack, or the sysadmin really needs to update their TLS support.

I think. (I'm not normally a server guy 😅)

**Comment by KuryKat** [comment]
Months later... still down, HTTPS returns ``ERR_SSL_VERSION_OR_CIPHER_MISMATCH`` and HTTP returns the Cloudflare error 1000

**Comment by Hexstream** [comment]
Frankly I am concerned Unlicense adoption could be impacted if this is not addressed promptly. I hate the idea of the Unlicense looking like an abandoned project.

**Comment by XtroTheArctic** [comment]
I sent this email to registrar-abuse@cloudflare.com which I found in this page: 

![image](https://github.com/unlicense/unlicense.org/assets/6631429/d282bfe9-7d8e-409f-b074-2ebea32ae42f)

![image](https://github.com/unlicense/unlicense.org/assets/6631429/79369d9a-104b-4069-8bf3-b45f12d16810)
![image](https://github.com/unlicense/unlicense.org/assets/6631429/d17f0b43-e3fc-40d5-b9db-cb1d811fc9b3)

**Comment by Hexstream** [comment]
Your email is painfully misguided.

First of all, there is no reason to believe he may be "dead or too sick".
A quick look at [his github contribution activity](https://github.com/artob) seems to dispel that notion.

Second, Cloudflare is an infrastructure provider. Pleading with them to restore the website is nonsensical in this instance, as the problem clearly does not lie at their level of responsibility.

Third, you are using a "report abuse" email address when you clearly have no intention of reporting abuse.

**Comment by XtroTheArctic** [comment]
I'm just trying to do something (anything) to resolve a problem which is affecting (maybe) thousands of people (including you and me too). I don't want this thread to become a s..tpost Internet argument so I'll just ignore your attitude. Have a nice day.

**Comment by KuryKat** [comment]
Actually I agree with @Hexstream, I understand you had your best intentions @XtroTheArctic but that's just not the best solution, asking Cloudflare to fix it isn't gonna change anything, specially if you send to the wrong email, they'll just rightfully ignore your message 😅😅

We just have to hope that @artob fixes this ASAP, we literally can't do anything, it's all on his hands, as the domain AND the organization it's under his name.

**Comment by Hexstream** [comment]
@XtroTheArctic I don't want this thread to become a s..tpost Internet argument so I'll just ignore your attitude. ;)

**Comment by ivanov17** [comment]
Has anyone tried writing @artob to his personal email?

**Comment by Hexstream** [comment]
I DM'd him about this on LinkedIn on 20 september and 27 october, no response.

**Comment by DreamHollow** [comment]
I'm upset that this project might be in jeopardy, I love the Unlicense and I've been using it in most of my projects.

**Comment by Hexstream** [comment]
Oh, wow!! Seems like [the site is finally back](https://unlicense.org/) [after ~5 months](https://web.archive.org/web/20230000000000*/https://unlicense.org/)!!

**Comment by XtroTheArctic** [comment]
Phew. It's a nice comeback.

**Comment by KuryKat** [comment]
Finally it's back XD

@kaizhu256 would you mind closing the Issue now that the website is back?

**Comment by kaizhu256** [comment]
Cool, closed and thx!
